// src/main/java/nl/claybytes/clibo/api/application/TimelineService.java

package nl.claybytes.clibo.api.application;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.transaction.Transactional;
import nl.claybytes.clibo.api.domain.model.TemporalBlock;
import nl.claybytes.clibo.api.domain.repository.TemporalBlockRepository;

import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.List;

@ApplicationScoped
public class TimelineService {

    @Inject
    TemporalBlockRepository repository;

    /**
     * Fetches all temporal blocks scheduled for today (00:00 to 23:59).
     */
    public List<TemporalBlock> getTodayTimeline() {
        LocalDateTime startOfDay = LocalDateTime.now().with(LocalTime.MIN);
        LocalDateTime endOfDay = LocalDateTime.now().with(LocalTime.MAX);

        return repository.find("startTime >= ?1 and startTime <= ?2 order by startTime asc", 
            startOfDay, endOfDay).list();
    }

    /**
     * Persists a new block generated by S.P.E.C.I.E.S.
     */
    @Transactional
    public void scheduleExecution(TemporalBlock block) {
        repository.persist(block);
    }
}
