global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'clibo-backend'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080'] # Points back to your WSL2 Quarkus app
