# Existing Channel Logic
# mp.messaging.incoming.words-in.auto.offset.reset=earliest
# mp.messaging.incoming.words-in.topic=words
# mp.messaging.outgoing.words-out.topic=words

# Connection to our Stable Docker-Compose Kafka
kafka.bootstrap.servers=localhost:9092

# New Channel Logic
mp.messaging.incoming.words-in.connector=smallrye-kafka
mp.messaging.incoming.words-in.auto.offset.reset=earliest
mp.messaging.incoming.words-in.topic=words

mp.messaging.outgoing.words-out.connector=smallrye-kafka
mp.messaging.outgoing.words-out.topic=words

# Disable DevServices so Quarkus doesn't spin up a second Kafka
quarkus.kafka.devservices.enabled=false